name: Home Server Deployment

on:
  push:
    branches:
      - main 

jobs:
  deploy-flask-app:
    runs-on: self-hosted 

    steps:
      - name: 📂 Checkout Code
        uses: actions/checkout@v4

      - name: 🐳 Build and Run with Docker
        run: |
          docker compose down
          docker compose build
          docker compose up -d
